### ISSUE TITLE
simcado.install_noise_cube() - KeyError

### ISSUE THREAD

**Issue by wzeil** [astronomyk/SimCADO#25]
simcado.install_noise_cube() results in the following error message:

>>> simcado.install_noise_cube()
WARNING - this process can take up to 10 minutes. Fear not!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wzeil/.local/lib/python3.4/site-packages/simcado/detector.py", line 1264, in install_noise_cube
    hdu = make_noise_cube(n, filename=None)
  File "/home/wzeil/.local/lib/python3.4/site-packages/simcado/detector.py", line 1220, in make_noise_cube
    cmds = commands.UserCommands()
  File "/home/wzeil/.local/lib/python3.4/site-packages/simcado/commands.py", line 252, in __init__
    self._default_data()
  File "/home/wzeil/.local/lib/python3.4/site-packages/simcado/commands.py", line 497, in _default_data
    if self.cmds["INST_SURFACE_FACTOR"] == "default":
KeyError: 'INST_SURFACE_FACTOR'

**Comment by oczoske** [comment]
I believe the offending line was removed in [this commit](https://github.com/astronomyk/SimCADO/commit/e3191a3e0cab67b5f85060c5ac49c255d5496447#diff-195e58afad51d1eebd5ab5affba333b7). Please try the latest github version.
